### ISSUE TITLE
In solution, under Second Iteration, incorrect parent entropy used

### ISSUE THREAD

**Issue by isobeldaley** [learn-co-curriculum/dsc-ID3-trees-lab#1]
Solution refers sets out parent classification as:

Play = [6,1]

However, it then uses play (NB: no capital) to calculate information gain.  This has earlier been defined as play = [9,5] under 1st iteration.  This leads to incorrect solution.

**Comment by sumedh10** [comment]
Thanks, @isobeldaley . This is now fixed.
